In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Scorecard Dataset.csv')
df.head()

STUDENT ID  1  2  3  4  5  6  7  8  9  ...  23  24  25  26  27  28  29  30  \
0   STUDENT1  2  2  3  3  1  2  2  1  1  ...   1   1   3   2   1   2   1   1   
1   STUDENT2  2  2  3  3  1  2  2  1  1  ...   1   1   3   2   3   2   2   3   
2   STUDENT3  2  2  2  3  2  2  2  2  4  ...   1   1   2   2   1   1   2   2   
3   STUDENT4  1  1  1  3  1  2  1  2  1  ...   1   2   3   2   2   1   3   2   
4   STUDENT5  2  2  1  3  2  2  1  3  1  ...   2   1   2   2   2   1   2   2   

   COURSE ID  GRADE  
0          1      1  
1          1      1  
2          1      1  
3          1      1  
4          1      1  

[5 rows x 33 columns]

In [3]:
df.drop(['STUDENT ID'], axis = 1, inplace = True)

In [4]:
df.rename(columns = {'1':'Student Age', '2':'Gender', '3':'High School Type', '4':'Scholarship','5':'Additional Work', '6':'Artistic or Sports Activity', '7':'Marital Status', '8':'Salary', '9':'Transportation', '10':'Accommodation', '11':"Mother's Education" , '12':"Father's Education", '13':'No. of Siblings', '14':'Parental Status', '15':"Mother's Occupation", '16':"Father's Occupation", '17':'Weekly Study Hours', '18':'Reading Frequency (Non - Scientific)', '19':'Reading Frequency (Scientific)', '20':'Attendance to Seminars/Conferences', '21':'Impact of Projects/Activities', '22':'Attendance to Classes', '23':'How do you prepare for exam?', '24':'When do you prepare for exam?','25':'Taking Notes', '26':'Listening', '27':'Improvement due to Discussion', '28':'Flip-Classroom', '29':'Cumulative GPA Last Semester', '30':'Expected GPA This Semester', 'GRADE':'Grade', 'COURSE ID':'Course ID'}, inplace = True)

In [5]:
df.columns

Index(['Student Age', 'Gender', 'High School Type', 'Scholarship',
       'Additional Work', 'Artistic or Sports Activity', 'Marital Status',
       'Salary', 'Transportation', 'Accommodation', 'Mother's Education',
       'Father's Education', 'No. of Siblings', 'Parental Status',
       'Mother's Occupation', 'Father's Occupation', 'Weekly Study Hours',
       'Reading Frequency (Non - Scientific)',
       'Reading Frequency (Scientific)', 'Attendance to Seminars/Conferences',
       'Impact of Projects/Activities', 'Attendance to Classes',
       'How do you prepare for exam?', 'When do you prepare for exam?',
       'Taking Notes', 'Listening', 'Improvement due to Discussion',
       'Flip-Classroom', 'Cumulative GPA Last Semester',
       'Expected GPA This Semester', 'Course ID', 'Grade'],
      dtype='object')

In [6]:
df.head()

Student Age  Gender  High School Type  Scholarship  Additional Work  \
0            2       2                 3            3                1   
1            2       2                 3            3                1   
2            2       2                 2            3                2   
3            1       1                 1            3                1   
4            2       2                 1            3                2   

   Artistic or Sports Activity  Marital Status  Salary  Transportation  \
0                            2               2       1               1   
1                            2               2       1               1   
2                            2               2       2               4   
3                            2               1       2               1   
4                            2               1       3               1   

   Accommodation  ...  How do you prepare for exam?  \
0              1  ...                             1   
1              1  ...                             1   
2              2  ...                             1   
3              2  ...                             1   
4              4  ...                             2   

   When do you prepare for exam?  Taking Notes  Listening  \
0                              1             3          2   
1                              1             3          2   
2                              1             2          2   
3                              2             3          2   
4                              1             2          2   

   Improvement due to Discussion  Flip-Classroom  \
0                              1               2   
1                              3               2   
2                              1               1   
3                              2               1   
4                              2               1   

   Cumulative GPA Last Semester  Expected GPA This Semester  Course ID  Grade  
0                             1                           1          1      1  
1                             2                           3          1      1  
2                             2                           2          1      1  
3                             3                           2          1      1  
4                             2                           2          1      1  

[5 rows x 32 columns]

In [7]:
df['Student Age'] = df['Student Age'].replace(1,'18-21')
df['Student Age'] = df['Student Age'].replace(2,'22-25')
df['Student Age'] = df['Student Age'].replace(3,'above 26')

In [8]:
df['Student Age'].unique()

array(['22-25', '18-21', 'above 26'], dtype=object)

In [9]:
df['Gender'] = df['Gender'].replace(1, 'Female')
df['Gender'] = df['Gender'].replace(2, 'Male')

In [10]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [11]:
df['High School Type'] = df['High School Type'].replace(1, 'Private')
df['High School Type'] = df['High School Type'].replace(2, 'State')
df['High School Type'] = df['High School Type'].replace(3, 'Other')

In [12]:
df['High School Type'].unique()

array(['Other', 'State', 'Private'], dtype=object)

In [13]:
df['Scholarship'] = df['Scholarship'].replace(1, 'None')
df['Scholarship'] = df['Scholarship'].replace(2, '25%')
df['Scholarship'] = df['Scholarship'].replace(3, '50%')
df['Scholarship'] = df['Scholarship'].replace(4, '75%')
df['Scholarship'] = df['Scholarship'].replace(5, 'Full')

In [14]:
df['Scholarship'].unique()

array(['50%', '75%', 'Full', '25%', 'None'], dtype=object)

In [15]:
df['Additional Work'] = df['Additional Work'].replace(1, 'Yes')
df['Additional Work'] = df['Additional Work'].replace(2, 'No')

In [16]:
df['Additional Work'].unique()

array(['Yes', 'No'], dtype=object)

In [17]:
df['Artistic or Sports Activity'] = df['Artistic or Sports Activity'].replace(1,'Yes')
df['Artistic or Sports Activity'] = df['Artistic or Sports Activity'].replace(2,'No')

In [18]:
df['Artistic or Sports Activity'].unique()

array(['No', 'Yes'], dtype=object)

In [19]:
df['Marital Status'] = df['Marital Status'].replace(1, 'Yes')
df['Marital Status'] = df['Marital Status'].replace(2, 'No')

In [20]:
df['Marital Status'].unique()

array(['No', 'Yes'], dtype=object)

In [21]:
df['Salary'] = df['Salary'].replace(1, 'USD 135-200')
df['Salary'] = df['Salary'].replace(2, 'USD 201-270')
df['Salary'] = df['Salary'].replace(3, 'USD 271-340')
df['Salary'] = df['Salary'].replace(4, 'USD 341-410')
df['Salary'] = df['Salary'].replace(5, 'USD above 410')

In [22]:
df['Salary'].unique()

array(['USD 135-200', 'USD 201-270', 'USD 271-340', 'USD 341-410',
       'USD above 410'], dtype=object)

In [23]:
df['Transportation'].unique()

array([1, 4, 2, 3], dtype=int64)

In [24]:
df['Transportation'] = df['Transportation'].replace(1, 'Bus')
df['Transportation'] = df['Transportation'].replace(2, 'Private Car/Taxi')
df['Transportation'] = df['Transportation'].replace(3, 'Bicycle')
df['Transportation'] = df['Transportation'].replace(4, 'Other')

In [25]:
df['Accommodation'].unique()

array([1, 2, 4, 3], dtype=int64)

In [26]:
df['Accommodation'] = df['Accommodation'].replace(1, 'Rental')
df['Accommodation'] = df['Accommodation'].replace(2, 'Dormitory')
df['Accommodation'] = df['Accommodation'].replace(3, 'With Family')
df['Accommodation'] = df['Accommodation'].replace(4, 'Other')

In [27]:
df["Mother\'s Education"].unique()

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [28]:
df["Mother\'s Education"] = df["Mother\'s Education"].replace(1, 'Primary School')
df["Mother\'s Education"] = df["Mother\'s Education"].replace(2, 'Secondary School')
df["Mother\'s Education"] = df["Mother\'s Education"].replace(3, 'High School')
df["Mother\'s Education"] = df["Mother\'s Education"].replace(4, 'University')
df["Mother\'s Education"] = df["Mother\'s Education"].replace(5, 'M.Sc.')
df["Mother\'s Education"] = df["Mother\'s Education"].replace(6, 'Ph.D')

In [29]:
df["Father\'s Education"].unique()

array([2, 3, 4, 5, 1, 6], dtype=int64)

In [30]:
df["Father\'s Education"] = df["Father\'s Education"].replace(1, 'Primary School')
df["Father\'s Education"] = df["Father\'s Education"].replace(2, 'Secondary School')
df["Father\'s Education"] = df["Father\'s Education"].replace(3, 'High School')
df["Father\'s Education"] = df["Father\'s Education"].replace(4, 'University')
df["Father\'s Education"] = df["Father\'s Education"].replace(5, 'M.Sc.')
df["Father\'s Education"] = df["Father\'s Education"].replace(6, 'Ph.D')

In [31]:
df['No. of Siblings'].unique()

array([3, 2, 5, 1, 4], dtype=int64)

In [32]:
df['No. of Siblings'] = df['No. of Siblings'].replace(1, '1')
df['No. of Siblings'] = df['No. of Siblings'].replace(2, '2')
df['No. of Siblings'] = df['No. of Siblings'].replace(3, '3')
df['No. of Siblings'] = df['No. of Siblings'].replace(4, '4')
df['No. of Siblings'] = df['No. of Siblings'].replace(5, '5 or above')

In [33]:
df['Parental Status'].unique()

array([1, 2, 3], dtype=int64)

In [34]:
df['Parental Status'] = df['Parental Status'].replace(1, 'Married')
df['Parental Status'] = df['Parental Status'].replace(2, 'Divorced')
df['Parental Status'] = df['Parental Status'].replace(3, 'Died - One of Them or Both')

In [35]:
df["Mother\'s Occupation"].unique()

array([2, 4, 3, 5, 1], dtype=int64)

In [36]:
df["Mother\'s Occupation"] = df["Mother\'s Occupation"].replace(1, 'Retired')
df["Mother\'s Occupation"] = df["Mother\'s Occupation"].replace(2, 'Housewife')
df["Mother\'s Occupation"] = df["Mother\'s Occupation"].replace(3, 'Govt. Officer')
df["Mother\'s Occupation"] = df["Mother\'s Occupation"].replace(4, 'Private Sector Officer')
df["Mother\'s Occupation"] = df["Mother\'s Occupation"].replace(5, 'Self Employed')

In [37]:
df["Father\'s Occupation"].unique()

array([5, 1, 4, 3, 2], dtype=int64)

In [38]:
df["Father\'s Occupation"] = df["Father\'s Occupation"].replace(1, 'Retired')
df["Father\'s Occupation"] = df["Father\'s Occupation"].replace(2, 'Govt. Officer')
df["Father\'s Occupation"] = df["Father\'s Occupation"].replace(3, 'Private Sector Officer')
df["Father\'s Occupation"] = df["Father\'s Occupation"].replace(4, 'Self Employed')
df["Father\'s Occupation"] = df["Father\'s Occupation"].replace(5, 'Other')

In [39]:
df['Weekly Study Hours'].unique()

array([3, 2, 1, 5, 4], dtype=int64)

In [40]:
df['Weekly Study Hours'] = df['Weekly Study Hours'].replace(1, 'None')
df['Weekly Study Hours'] = df['Weekly Study Hours'].replace(2, '<5 Hours')
df['Weekly Study Hours'] = df['Weekly Study Hours'].replace(3, '6-10 Hours')
df['Weekly Study Hours'] = df['Weekly Study Hours'].replace(4, '11-20 Hours')
df['Weekly Study Hours'] = df['Weekly Study Hours'].replace(5, 'More than 20 Hours')

In [41]:
df['Reading Frequency (Non - Scientific)'].unique()

array([2, 1, 3], dtype=int64)

In [42]:
df['Reading Frequency (Non - Scientific)'] = df['Reading Frequency (Non - Scientific)'].replace(1, 'None')
df['Reading Frequency (Non - Scientific)'] = df['Reading Frequency (Non - Scientific)'].replace(2, 'Sometimes')
df['Reading Frequency (Non - Scientific)'] = df['Reading Frequency (Non - Scientific)'].replace(3, 'Often')

In [43]:
df['Reading Frequency (Scientific)'].unique()

array([2, 1, 3], dtype=int64)

In [44]:
df['Reading Frequency (Scientific)'] = df['Reading Frequency (Scientific)'].replace(1, 'None')
df['Reading Frequency (Scientific)'] = df['Reading Frequency (Scientific)'].replace(2, 'Sometimes')
df['Reading Frequency (Scientific)'] = df['Reading Frequency (Scientific)'].replace(3, 'Often')

In [45]:
df['Attendance to Seminars/Conferences'].unique()

array([1, 2], dtype=int64)

In [46]:
df['Attendance to Seminars/Conferences'] = df['Attendance to Seminars/Conferences'].replace(1, 'Yes')
df['Attendance to Seminars/Conferences'] = df['Attendance to Seminars/Conferences'].replace(2, 'No')

In [47]:
df['Impact of Projects/Activities'].unique()

array([1, 3, 2], dtype=int64)

In [48]:
df['Impact of Projects/Activities'] = df['Impact of Projects/Activities'].replace(1, 'Positive')
df['Impact of Projects/Activities'] = df['Impact of Projects/Activities'].replace(2, 'Negative')
df['Impact of Projects/Activities'] = df['Impact of Projects/Activities'].replace(3, 'Neutral')

In [49]:
df['Attendance to Classes'].unique()

array([1, 2], dtype=int64)

In [50]:
df['Attendance to Classes'] = df['Attendance to Classes'].replace(1, 'Always')
df['Attendance to Classes'] = df['Attendance to Classes'].replace(2, 'Sometimes')

In [51]:
df['How do you prepare for exam?'].unique()

array([1, 2, 3], dtype=int64)

In [52]:
df['How do you prepare for exam?'] = df['How do you prepare for exam?'].replace(1, 'Alone')
df['How do you prepare for exam?'] = df['How do you prepare for exam?'].replace(2, 'With Friends')
df['How do you prepare for exam?'] = df['How do you prepare for exam?'].replace(3, 'Not Applicable')

In [53]:
df['When do you prepare for exam?'].unique()

array([1, 2, 3], dtype=int64)

In [54]:
df['When do you prepare for exam?'] = df['When do you prepare for exam?'].replace(1, 'Closest Date to the Exam')
df['When do you prepare for exam?'] = df['When do you prepare for exam?'].replace(2, 'Regularly During the Semester')
df['When do you prepare for exam?'] = df['When do you prepare for exam?'].replace(3, 'Never')

In [55]:
df['Taking Notes'].unique()

array([3, 2, 1], dtype=int64)

In [56]:
df['Taking Notes'] = df['Taking Notes'].replace(1, 'Never')
df['Taking Notes'] = df['Taking Notes'].replace(2, 'Sometimes')
df['Taking Notes'] = df['Taking Notes'].replace(3, 'Always')

In [57]:
df['Listening'].unique()

array([2, 3, 1], dtype=int64)

In [58]:
df['Listening'] = df['Listening'].replace(1, 'Never')
df['Listening'] = df['Listening'].replace(2, 'Sometimes')
df['Listening'] = df['Listening'].replace(3, 'Always')

In [59]:
df['Improvement due to Discussion'].unique()

array([1, 3, 2], dtype=int64)

In [60]:
df['Improvement due to Discussion'] = df['Improvement due to Discussion'].replace(1, 'Never')
df['Improvement due to Discussion'] = df['Improvement due to Discussion'].replace(2, 'Sometimes')
df['Improvement due to Discussion'] = df['Improvement due to Discussion'].replace(3, 'Always')

In [61]:
df['Flip-Classroom'].unique()

array([2, 1, 3], dtype=int64)

In [62]:
df['Flip-Classroom'] = df['Flip-Classroom'].replace(1, 'Not Useful')
df['Flip-Classroom'] = df['Flip-Classroom'].replace(2, 'Useful')
df['Flip-Classroom'] = df['Flip-Classroom'].replace(3, 'Not Applicable')

In [63]:
df['Cumulative GPA Last Semester'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [64]:
df['Cumulative GPA Last Semester'] = df['Cumulative GPA Last Semester'].replace(1, '<2.00')
df['Cumulative GPA Last Semester'] = df['Cumulative GPA Last Semester'].replace(2, '2.00-2.49')
df['Cumulative GPA Last Semester'] = df['Cumulative GPA Last Semester'].replace(3, '2.50-2.99')
df['Cumulative GPA Last Semester'] = df['Cumulative GPA Last Semester'].replace(4, '3.00-3.49')
df['Cumulative GPA Last Semester'] = df['Cumulative GPA Last Semester'].replace(5, 'above 3.49')

In [65]:
df['Expected GPA This Semester'].unique()

array([1, 3, 2, 4], dtype=int64)

In [66]:
df['Expected GPA This Semester'] = df['Expected GPA This Semester'].replace(1, '<2.00')
df['Expected GPA This Semester'] = df['Expected GPA This Semester'].replace(2, '2.00-2.49')
df['Expected GPA This Semester'] = df['Expected GPA This Semester'].replace(3, '2.50-2.99')
df['Expected GPA This Semester'] = df['Expected GPA This Semester'].replace(4, '3.00-3.49')

In [67]:
df['Grade'].unique()

array([1, 2, 5, 0, 3, 4, 7, 6], dtype=int64)

In [68]:
df['Grade'] = df['Grade'].replace(0, 'Fail')
df['Grade'] = df['Grade'].replace(1, 'DD')
df['Grade'] = df['Grade'].replace(2, 'DC')
df['Grade'] = df['Grade'].replace(3, 'CC')
df['Grade'] = df['Grade'].replace(4, 'CB')
df['Grade'] = df['Grade'].replace(5, 'BB')
df['Grade'] = df['Grade'].replace(6, 'BA')
df['Grade'] = df['Grade'].replace(7, 'AA')

In [69]:
df.to_csv('Scorecard.csv', index = False)